name: Moby Benchmark
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "33 02 * * *"

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init moby

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v6
        with:
          context: ./moby
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  nscloud-build:
    name: Build with Namespace
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init moby

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0
        with:
          load-to-docker: false

      - name: Avoid Dockerhub pull limits
        run: |
          sed -i 's=https://registry-1.docker.io=169.254.169.43:6001=g' ./moby/contrib/download-frozen-image-v2.sh

      - uses: docker/build-push-action@v6
        with:
          context: ./moby
          platforms: linux/amd64,linux/arm64

  nsc-build-namespace-runners:
    name: Build with Namespace - on Namespace runners
    runs-on: nscloud-ubuntu-22.04-amd64-2x8
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init moby

      - name: Avoid Dockerhub pull limits
        run: |
          sed -i 's=https://registry-1.docker.io=169.254.169.43:6001=g' ./moby/contrib/download-frozen-image-v2.sh

      - uses: docker/build-push-action@v6
        with:
          context: ./moby
          platforms: linux/amd64,linux/arm64

  notify-failures:
    name: Notify on build failures
    needs:
      - docker-build
      - nscloud-build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: failure() && needs.docker-build.result == 'success' && needs.nscloud-build.result == 'failure'
    steps:
      - uses: ruby/action-slack@v3.2.1
        with:
          payload: |
            {
              "attachments": [{
                "title": "Namespace build failed while Docker build passed! Check now: ${{ job.status }}: ${{ github.workflow }}",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "See the link",
                "fields": [],
                "footer": "",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
